name: Run Selenium Script

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Google Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: latest

      - name: Set up virtual display (Xvfb)
        run: |
          export DISPLAY=:99
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          sleep 3

      - name: Install dependencies
        run: |
          pip install selenium
          pip install webdriver-manager
          pip install pytest

      - name: Run your test script
        run: |
          export DISPLAY=:99
          python run_test.py
