name: My actions have consequence

on: [push]

jobs:
  run-selenium-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Use a stable version

      - name: Set up Chrome and ChromeDriver
        uses: nanasess/setup-chromedriver@v2
        with:
          chromedriver-version: 'latest'

      - name: Start Xvfb (virtual display)
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          Xvfb :99 -ac -screen 0 1280x1024x24 > /dev/null 2>&1 &
          echo "DISPLAY=:99" >> $GITHUB_ENV

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium pytest webdriver-manager

      - name: Add current directory to PYTHONPATH
        run: echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV

      - name: Run Selenium tests
        run: python run_test.py

      - name: Show success message
        run: echo "✅ Tests completed!"
