name: My actions have consequence

on: [push]

jobs:
  ega:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Set up ChromeDriver
        uses: nanasess/setup-chromedriver@v2
        with:
          chromedriver-version: '135.0.7049.84'
          chromeapp: chrome

      - name: Set up virtual display (Xvfb)
        run: |
          export DISPLAY=:99
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          sleep 3  # Give Xvfb time to start

      - name: Install dependencies
        run: |
          pip install selenium
          pip install pytest

      - name: Run tests
        run: |
          export DISPLAY=:99
          python run_test.py
